<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EventHub.Domain\EventHub.Domain.csproj" />
    <ProjectReference Include="..\EventHub.Application\EventHub.Application.csproj" />
    <ProjectReference Include="..\EventHub.Infrastructure\EventHub.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
